baseURL = "https://rootdeep.github.io/"
title = "RootDeep"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh-cn"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
hello = "Hi, I'm Zhiguo Li"
logo = "rootdeep.jpg"

[[Params.bigimg]]
src = "furongyuan.jpg"
desc = "The night scenes in in Xi'an Tang Paradise, Mar 10, 2017"

[Author]
  email = "zhiguo.lee@foxmail.com"
  github = "zhiguo.lee"
  weibo = "weibo_username"
  wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  facebook = "facebook_username"
  google = "googlplus_id_number"
  instagram = "instagram_username"


[[menu.main]]
    identifier = "Home"
    name = "Home"
    weight = 1
	url = "/"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 1
    
[[menu.main]]
    parent = "Categories"
    name = "Linux Practice"
    url = "categories/linux-practice"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "OpenStack"
    url = "categories/openstack"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Github"
    url = "categories/github"
    weight = 4	

[[menu.main]]
    parent = "Categories"
    name = "Devops"
    url = "categories/devops"
    weight = 5

[[menu.main]]
    identifier = "Gitbooks"
    name = "Gitbooks"
    weight = 3

[[menu.main]]
    parent = "Gitbooks"
    name = "Kubernetes handbook"
    url = "kubernetes-handbook"
    weight = 1

[[menu.main]]
    parent = "Gitbooks"
    name = "Docker handbook"
    url = "docker-handbook"
    weight = 2
	
[[menu.main]]
    parent = "Gitbooks"
    name = "Oz Tool"
    url = "simple-operation-of-oz-tool"
    weight = 3

[[menu.main]]
    name = "About"
    url = "about"
    weight = 6



