baseURL = "https://rootdeep.github.io/"
title = "RootDeep"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
commit = false
comments = true
logo = "rootdeep.jpg"

[Author]
  name = "Zhiguo Li"
  website = "https://rootdeep.github.io/"
  github = "rootdeep"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 1
    
[[menu.main]]
    parent = "Categories"
    name = "Linux Practice"
    url = "categories/linux-practice"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "OpenStack"
    url = "categories/openstack"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Github"
    url = "categories/github"
    weight = 4	

[[menu.main]]
    parent = "Categories"
    name = "Devops"
    url = "categories/devops"
    weight = 5

[[menu.main]]
    identifier = "Gitbooks"
    name = "Gitbooks"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "k8s sourcecode analysis"
    url = "k8s-source-code-analysis"
    weight = 1

[[menu.main]]
    parent = "Gitbooks"
    name = "Docker handbook"
    url = "docker-handbook"
    weight = 2
	
[[menu.main]]
    parent = "Gitbooks"
    name = "Oz Tool"
    url = "simple-operation-of-oz-tool"
    weight = 3



